substitutions:
  devicename: padlight32
  u_devicename: "Padlight32 keyboard"
  platform: esp32
  board: wemos_d1_mini32
  arm_delay_max: "15"
  location: in # in/out = indoors/outdoors
  relay_present: "true"
  relay_name: Relay # give a name to the relay, let's say Gate, Door, etc. It must be defined even if it's not present.
  relay_pw: "3659" # max length 6 digit

  out_temp: "sensor.rpi1_ble_outdoors_lywsd03mmc_temperature"
  out_hum: "sensor.rpi1_ble_outdoors_lywsd03mmc_humidity"
  in_temp: "sensor.rpi1_ble_downstairs_lywsd03mmc_temperature"
  in_hum: "sensor.rpi1_ble_downstairs_lywsd03mmc_humidity"

  output_platform: ledc
  output_pin: '23'
  status_led: '16'
  relay_pin: '18'
  led_pin: '19'
  sda_pin: '21'
  scl_pin: '22'

<<: !include "!pads/pad_common.yaml"

wifi:
  networks:
  # fast_connect: on 
  - ssid: "OixCanCasicaRouter"
    password: "polclotagou10"
  - ssid: "Oix-AP(2.4G)"
    password: "polclotagou10"
