substitutions:
  devicename: padofi
  u_devicename: "Office Pad OLED keyboad"
  platform: ESP8266
  board: d1_mini
  arm_delay_max: "15"
  location: in # in/out = indoors/outdoors
  
  relay_present: "false"
  relay_name: "" # give a name to the relay, let's say Gate, Door, etc. It must be defined even if it's not present.
  relay_pw: "" # max length 6 digit
  
  out_temp: "sensor.lywsd03mmc_3_temperature"
  out_hum: "sensor.lywsd03mmc_3_humidity"
  in_temp: "sensor.lywsd03mmc_1_temperature"
  in_hum: "sensor.lywsd03mmc_1_humidity"

  output_platform: esp8266_pwm
  output_pin: D7
  status_led: D4
  relay_pin: D5
  led_pin: D6
  sda_pin: D2
  scl_pin: D1

<<: !include "!pads/pad_common.yaml"

wifi:
  fast_connect: true
  networks:
  - ssid: "OixCanCasicaRouter"
    password: "polclotagou10"


